name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-train-serve:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Unit tests (fast)
        run: pytest -q

      - name: Train model
        run: python src/train.py --data data/bugs.csv --outdir models

      - name: QA gate (compare to baseline)
        run: python scripts/qa_gate.py

      - name: Start API (background)
        run: |
          nohup uvicorn src.api:app --host 127.0.0.1 --port 8000 > uvicorn.log 2>&1 &
          sleep 3

      - name: Wait for /health
        run: |
          for i in {1..20}; do
            if curl -s http://127.0.0.1:8000/health | grep -q '"model_loaded": true'; then
              echo "API is ready"; exit 0;
            fi
            sleep 1
          done
          echo "API not ready"; cat uvicorn.log; exit 1

      - name: API smoke tests
        env:
          BASE_URL: http://127.0.0.1:8000
        run: pytest -q tests/test_api_smoke.py

      - name: Upload metrics artifact
        uses: actions/upload-artifact@v4
        with:
          name: metrics-json
          path: models/metrics.json

      - name: Docker build (validation)
        run: docker build -t mlops-qa-bugseverity:ci -f docker/Dockerfile .

