name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-train-serve:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run only fast tests that don't require artifacts/API
      - name: Unit tests (fast)
        run: pytest -q -m "not integration"

      - name: Train model
        run: python src/train.py --data data/bugs.csv --outdir models

      - name: QA gate (compare to baseline)
        run: python scripts/qa_gate.py

      - name: Start API (background)
        run: |
          echo "PWD=$(pwd)"
          ls -l
          ls -l models || true
          test -f models/model.joblib || (echo "model missing"; exit 1)
          nohup uvicorn src.api:app --host 127.0.0.1 --port 8000 > uvicorn.log 2>&1 &
          sleep 3
          echo "---- uvicorn.log (tail) ----"
          tail -n +1 uvicorn.log | sed -n '1,40p' || true

      - name: Wait for /health
        run: |
          for i in {1..20}; do
            BODY=$(curl -s http://127.0.0.1:8000/health || true)
            echo "Health: $BODY"
            echo "$BODY" | grep -E -q '"model_loaded":[[:space:]]*true' && { echo "API is ready"; exit 0; }
            sleep 1
          done
          echo "API not ready"
          echo "---- uvicorn.log ----"
          cat uvicorn.log
          exit 1


      # Now run integration tests (artifact checks + API smoke)
      - name: Integration tests (artifacts + API)
        env:
          BASE_URL: http://127.0.0.1:8000
        run: pytest -q -m integration

      - name: Upload metrics artifact
        uses: actions/upload-artifact@v4
        with:
          name: metrics-json
          path: models/metrics.json

      - name: Docker build (validation)
        run: docker build -t mlops-qa-bugseverity:ci -f docker/Dockerfile .

